config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Mock ups
  get 'mockups/index'
  get 'mockups/show'


  get '/drummers' => 'drummers#index', as: :drummers
  get '/drummers/:id' => 'drummers#show', as: :drummer




  root 'drummers#index'


end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base

  devise :database_authenticatable, :trackable, :validatable, :lockable, :timeoutable
end

app/models/bassist.rb
class Bassist < ActiveRecord::Base

  validates :name, presence: true

end

app/models/cymbal_brand.rb
class CymbalBrand < ActiveRecord::Base

  validates :name, presence: true

  has_many :drummers

end

app/models/drumkit.rb
class Drumkit < ActiveRecord::Base

  validates :name, presence: true

  has_many :drummers

end

app/models/drummer.rb
class Drummer < ActiveRecord::Base

  validates :name, presence: true

  belongs_to :drumkit
  belongs_to :stick
  belongs_to :genre
  belongs_to :cymbal_brand

  mount_uploader :photo, PhotoUploader


end

app/models/genre.rb
class Genre < ActiveRecord::Base

  validates :name, presence: true

  has_many :drummers

end

app/models/stick.rb
class Stick < ActiveRecord::Base

  validates :name, presence: true

  has_many :drummers

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drummers_controller.rb
class DrummersController < ApplicationController

  def index
    @drummers = Drummer.all
  end

  def show
    @drummer = Drummer.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/mockups_controller.rb
class MockupsController < ApplicationController

  def index

  end

  def show

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drummers/index.html.erb
<div class="container-fluid">
  <div class="col-md-12">
    <div class="jumbotron">
      <h1>Favorite Drummers</h1>

      <p>
        Welcome to Fum, an extensive directory of drummers. Find out about your favorite drummers, explore drummers, share
        and on and on and on...
      </p>

      <p><a class="btn btn-primary btn-lg" href="#" role="button">Sign Up</a></p>
    </div>
  </div>
</div>

<div id="browse-body">

  <div class="drummer-tab">
    <% @drummers.each do |drummer| %>
      <div class="col-md-4">
        <div class="thumbnail">
          <%= image_tag drummer.photo.url, alt: drummer.name %>
          <div class="caption">
            <h3><%= drummer.name %></h3>

            <p><%= truncate(drummer.bio, :omission => "...", :length => 150) %></p>

            <h4><strong>Drumkit Make</strong></h4>

            <p><%= drummer.drumkit.name if drummer.drumkit %></p>


            <h4><strong>Cymbals</strong></h4>
            <p><%= drummer.cymbal_brand.name if drummer.cymbal_brand %></p>



            <h4><strong>Sticks</strong></h4>
            <p><%= drummer.stick.name if drummer.stick %></p>


           <%= link_to "Read More", drummer_path(drummer), :class => "btn btn-primary" %>

          </div>
        </div>

      </div>
    <% end %>
  </div>


</div>

app/views/drummers/show.html.erb
  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag @drummer.photo.url, alt: @drummer.name %>
    </div>
  </div>

  <div class="col-md-4">
    <h2><%= @drummer.name %></h2></br>
    <h2><%= @drummer.drumkit.name if @drummer.drumkit %></h2>
  </div>

app/views/home/index.html.erb
<div class="page-header">
  <h1>Example page header <small>Subtext for header</small></h1>
</div>

<h1>My Fummer</h1>

<p>First paragraph</p>

<%= @drummer %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= render partial: 'shared/header' %>
      <div class="notice"><%= notice %></div>
      <div class="alert"><%= alert %></div>
      <%= yield %>
      <%= render partial: 'shared/footer' %>
    </div>
  </div>
</div>

</body>
</html>

app/views/mockups/index.html.erb
<div class="container-fluid">
  <div class="col-md-8">
    <div class="jumbotron">
      <h1>Favorite Drummers</h1>

      <p>
        Welcome to Fum, an extensive directory of drummers. Find out about your favorite drummers, explore drummers, share
        and on and on and on...
      </p>

      <p><a class="btn btn-primary btn-lg" href="#" role="button">Sign Up</a></p>
    </div>
  </div>
  <div class="col-md-4">
    <div class="list-group">
      <a href="#" class="list-group-item active">
        Most Popular Drummers:
      </a>
      <a href="#" class="list-group-item">Chad Smith</a>
      <a href="#" class="list-group-item">Chris Coleman</a>
      <a href="#" class="list-group-item">Phil Collins</a>
      <a href="#" class="list-group-item">Peter Erksine</a>
      <a href="#" class="list-group-item">Dave Wekyl</a>
      <a href="#" class="list-group-item">Matt Cameron</a>


    </div>
  </div>
</div>

<div class="container-fluid">
  <div id="search">
    <div class="row">
      <div class="col-md-3">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for drummers...">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">Go!</button>
      </span>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid" id="browse-body">

  <div class="col-md-4">
      <div class="thumbnail">
        <%= image_tag "carter_beauford.jpg", alt: "Carter Beauford" %>
        <div class="caption">
          <h3>Carter Carter Beauford</h3>

          <p>Carter Anthony Beauford is an American drummer, percussionist, and founding member of Dave Matthews Band.
            He is known for his ability to adapt to a variety of genres, and both his ambidextrous and his open hand
            drumming styles.</p>
          <a href="#" class="btn btn-primary" role="button">Read More</a>
        </div>
      </div>
  </div>


  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag "jon_fishman.jpg", alt: "Jon Fishman" %>
      <div class="caption">
        <h3>Jon Fishman</h3>

        <p>Carter Anthony Beauford is an American drummer, percussionist, and founding member of Dave Matthews Band.
          He is known for his ability to adapt to a variety of genres, and both his ambidextrous and his open hand
          drumming styles.</p>
        <a href="#" class="btn btn-primary" role="button">Read More</a>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag "matt_cameron.jpg", alt: "Matt Cameron" %>
      <div class="caption">
        <h3>Matt Cameron</h3>

        <p>Carter Anthony Beauford is an American drummer, percussionist, and founding member of Dave Matthews Band.
          He is known for his ability to adapt to a variety of genres, and both his ambidextrous and his open hand
          drumming styles.</p>
        <a href="http://www.alternativenation.net/who-will-replace-matt-cameron-for-soundgardens-2014-tour/"
           target="_blank" class="btn btn-primary" role="button">Read More</a>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag "dave-grohl.jpg", alt: "Dave Grhol" %>
      <div class="caption">
        <h3>Dave Grohl</h3>

        <p>Carter Anthony Beauford is an American drummer, percussionist, and founding member of Dave Matthews Band.
          He is known for his ability to adapt to a variety of genres, and both his ambidextrous and his open hand
          drumming styles.</p>
        <a href="#" class="btn btn-primary" role="button">Read More</a>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag "tony_royster.jpg", alt: "Tony Royster" %>
      <div class="caption">
        <h3>Tony Royster Jr.</h3>

        <p>Carter Anthony Beauford is an American drummer, percussionist, and founding member of Dave Matthews Band.
          He is known for his ability to adapt to a variety of genres, and both his ambidextrous and his open hand
          drumming styles. </p>
        <a href="#" class="btn btn-primary" role="button">Read More</a>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag "bill_bruford.jpg", alt: "Bill Bruford" %>
      <div class="caption">
        <h3>Bill Bruford</h3>

        <p>Carter Anthony Beauford is an American drummer, percussionist, and founding member of Dave Matthews Band.
          He is known for his ability to adapt to a variety of genres, and both his ambidextrous and his open hand
          drumming styles.</p>
        <a href="http://www.alternativenation.net/who-will-replace-matt-cameron-for-soundgardens-2014-tour/"
           target="_blank" class="btn btn-primary" role="button">Read More</a>
      </div>
    </div>
  </div>
</div>

app/views/mockups/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">

      <%= image_tag "carter_beauford.jpg", alt: "Carter Beauford" %>

      <h2>Carter Beauford</h2>

      <div id="main-bio-text">
        <p>
          Beauford was first exposed to the drums at age three. At the time, his father had bought tickets to a Buddy
          Rich
          concert and could not find someone to watch his son, so he took young Beauford along to the show. Beauford was
          mesmerized by Buddy Rich on stage. After that show, Beauford's father bought his son a tin drum set with paper
          heads, since Beauford showed so much interest in learning the instrument. Beauford began performing
          professionally
          when he was nine
        </p>

        <p>
          Beauford explains his unusual playing style in his instructional video "Under The Table & Drumming",
          attributing
          his use of left-hand-lead on a right-handed kit to playing his own kit in front of a mirror as a child in an
          attempt to emulate his favorite drummers, like Buddy Rich. He unknowingly set up his drums in reverse of
          whichever
          performer and set that he had in mind, in an attempt to make the mirrored image of himself match that of the
          audience's perspective, as he had seen it on stage and TV. This helped him to become completely ambidextrous
          at a
          very early age, albeit by accident.[citation needed]

          Beauford earned a degree in Occupational Therapy
        </p>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
      <p><strong>Notable Groups</strong></p>

      <p>
        Dave Matthews Band, Secrets
      </p>
    </div>
  </div>

</div>

app/views/shared/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom navbar-inverse" >
  <div class="container-fluid">
    <div class="navbar-header">
      <ul class="nav nav-pills">
        <li role="presentation" class="active"><a href="#">Home</a></li>
        <li role="presentation"><a href="#">Holder</a></li>
        <li role="presentation"><a href="#">Holder</a></li>
      </ul>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" >
  <div class="container-fluid">
    <div class="navbar-header">
      <ul class="nav nav-pills">
        <li role="presentation" class="active"><%= link_to "Home", root_path %></li>
        <li role="presentation"><%= link_to 'Admin', admin_root_path, target: blank?%></li>
      </ul>
      </ul>
    </div>
    <a class="navbar-brand" href="#"></a>

  </div>
</nav>

app/views/shared/side_bar.html.erb
<div class="col-lg-6">
  <div class="input-group">
      <span class="input-group-addon">
        <input type="radio" aria-label="one">
      </span>
    <input type="text" class="form-control" aria-label="two">
  </div>
</div>